name: Gen-readme

on:
  push:
  
jobs:
  markscribe:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update readme
        run: >
          python scripts/render_template.py
          --work-dir ${{github.workspace}}
          --tmpl-dir templates
          --tmpl-name README.md.tpl
          --cnfg-path config.json
          --dest-path README.md

      - name: Setup git
        ru: |
          git config --global.user "Render Bot - Readme"
          git config --global.email "readme@render.bot"
          # git remote set-url origin https://github.com/cklyne/cklyne.git

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add README.md
          git commit -m "Rendered README.md again based on new configs."
          git push --set-upstream https://cklyne:$GITHUB_TOKEN@github.com/cklyne/cklyne.git
        # uses: stefanzweifel/git-auto-commit-action@4
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   commit_message: Updated generated readme-scribe
        #   branch: master
        #   commit_user_name: readme-scribe :bot
        #   commit_user_email: actions@github.com
        #   commit_author: readme-scribe :bot <actions@github.com>

      # - name: Commit changes
        # uses: stefanzweifel/git-auto-commit-action@4
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   commit_message: Updated generated readme-scribe
        #   branch: master
        #   commit_user_name: readme-scribe :bot
        #   commit_user_email: actions@github.com
        #   commit_author: readme-scribe :bot <actions@github.com>
