name: Gen-readme

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/gen_readme.yml
      - scripts/render_template.py
      - requirements.txt
      - config.json
      - templates/*
      - "!README.md"
  
jobs:
  Render_Readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Update readme
        run: >
          python scripts/render_template.py
          --work-dir ${{github.workspace}}
          --tmpl-dir templates
          --tmpl-name README.md.tpl
          --cnfg-path config.json
          --dest-path README.md

      - name: Setup git
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh auth setup-git
          git config --global user.name "Render Bot - Readme"
          git config --global user.email "readme@render.bot"

      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add README.md
          git commit -m "Rendered README.md again based on new configs."
          git push --set-upstream https://github.com/cklyne/cklyne.git
